# This config file is where you can add your own custom compressors to the game.
# Make each new compressor "compressor#", where # is a number incremented by 1 from the previous compressor.
# MAKE SURE to include at least the display-name and material parameters for each compressor.

compressors:
  compressor1:
    display-name: '§6§kaa§r§6 Auto Compressor §kaa§r'
    lore:
      - '§7§oAutomatically compresses these items:'
      - '§3  Diamonds -> Block of Diamond'
      - '§4  Redstone -> Block of Redstone'
      - '§6  Gold -> Block of Gold'
      - '§7  Iron -> Block of Iron'
    material: diamond_block
    enchant-glint: true
    compress-groups:
      group1:
        start-item: diamond
        end-item: diamond_block
        compress-amount: 9

  compressor2:
    display-name: 'Compressor of Automagic'
    material: sculk_sensor
  compressor3:
    display-name: '§cCOmP'
    lore:
      - "It is unknown what this item will do when right clicked..."
    material: gold_ingot
    enchant-glint: true