# This config file is where you can add your own custom compressors to the game.
# Make each new compressor "compressor#", where # is a number incremented by 1 from the previous compressor.

compressors:
  compressor1:
    display-name: '§6§kaa§r§6 Auto Compressor §kaa§r'
    lore:
      - '§7§oAutomatically compresses these items:'
      - '§3  Diamonds -> Block of Diamond'
      - '§4  Redstone -> Block of Redstone'
      - '§6  Gold -> Block of Gold'
      - '§7  Iron -> Block of Iron'
    material: 'diamond_block'
    enchant-glint: true
    stackable: false