name: AutoCompressors
version: '${project.version}'
main: io.github.rainpaw.autocompressors.AutoCompressors
api-version: '1.20'
authors: [rainpaw10]
description: A Spigot plugin that adds highly customizable item compressors.
website: rainpaw.github.io
commands:
  getcompressor:
    description: Gives player the specified auto compressor.
    usage: /<command>
    aliases: givecompressor
    permission: autocompressors.getcompressor
    permission-message: You don't have permission to run this command.
  autocompressorsreload:
    description: Reloads the config.yml of the plugin..
    usage: /<command>
    aliases: acr
    permission: autocompressors.reload
    permission-message: You don't have permission to run this command.
  editcompressors:
    description: Opens a GUI allowing compressors to be edited in-game.
    usage: /<command>
    aliases: editcomps
    permission: autocompressors.editcompressors
    permission-message: You don't have permission to run this command.